version: '3'

services:
    api:
        build: ./api
        volumes:
            - ./api:/var/www
        depends_on:
            - db
            - smtp

    web:
        image: nginx
        ports:
            - 8889:80
        volumes:
            - ./api:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api

    nuxt:
        image: node:12.4-alpine
        working_dir: /var/www
        environment:
            - HOST=0.0.0.0
        ports:
            - 8888:3000
        volumes:
            - ./client:/var/www
        command: sh -c "yarn install && yarn dev"

    db:
        image: mysql:5.7
        environment:
            # Password for root access
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/appdata:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 9000:3306

    smtp:
        image: rnwood/smtp4dev:linux-amd64-v3
        ports:
            - 3000:80